### ISSUE TITLE
大佬，能做个 dumi 的 vuepress 主题吗?

### ISSUE THREAD

**Issue by xrkffgg** [OrekiSH/vuepress-dumi#1]
😎

**Comment by OrekiSH** [comment]
感觉你这个需求受众太少了，theme-default它不香吗？手动@PeachScript(doge

**Comment by PeachScript** [comment]
要是能把主题市场搞出来就更香了😍
dumi-theme-antd
dumi-theme-antv
dumi-theme-material
dumi-theme-semantic
dumi-theme-vuepress
dumi-theme-yy
...

**Comment by OrekiSH** [comment]
有道理哦，整

**Comment by OrekiSH** [comment]
VuePress的写了，先关了哦@xrkffgg  https://github.com/OrekiSH/dumi-theme
